apiVersion : apps/v1
kind: Deployment
metadata:
  name: "matkuber-bf41"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "matkuber-bf41"
  template:
    metadata:
      labels:
        app: "matkuber-bf41"
    spec:
      containers:
        - name: "matkuber-bf41"
          image: "matacr.azurecr.io/matkuber"
          ports:
          - containerPort: 80