apiVersion: v1
kind: Service
metadata:
    name: "matkuber-bf41"
    labels:
        app: "matkuber-bf41"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "matkuber-bf41"